### ISSUE TITLE
issue on clear()

### ISSUE THREAD

**Issue by Wingsofcourage** [BojanJurca/Key-value-pairs-for-Arduino#2]
If i clear and and refill the content the size becomes negativ.

The size during __clear__() method in line 686 is reduced by one.
I guess the size needs to be set to zero in this line. 

At the end of the recursive delete the size should be set to 0.

**Comment by BojanJurca** [comment]
Indeed. Thank you for noticing. I will fix this soon.

**Comment by BojanJurca** [comment]
Would you please provide the code that reproduces the bug? I can see that there is a bug but it is not in the clear () function. This would help me identify the rot cause of the  problem.

**Comment by Wingsofcourage** [comment]
I can provide the code, but it's not helpful for you, because i parse data from a stream. 
But i can describe it.
loop(){ 
  While (key = read from stream) {
    // Check existence in the key value store
    if (keyValueStore->find (key) != NULL) {
      // Delete the key 
      keyValueStore->erase(key);
    }

    // insert measurement to key value store
    keyValueStore->insert(key,(String)value);
  }
  process the key value store
  kvs.clear()
}

**Comment by BojanJurca** [comment]
What I found so far is that the problem really lies in the erase() function. I will continue working on it tomorrow.

**Comment by Wingsofcourage** [comment]
it took me a while, but this code will get negative returns for size after a couple of seconds

`for (int i = 0; i <= 1000 ; i++){
  Serial.println("-----");
  Serial.println(keyValueStore.size());
  // fill the store
  for (int y = 550; y <= 800; y++) {
    keyValueStore.insert(y,"bla");
  }

  //make updates
  for (int q = 1; q <= 200; q++){
    int r =  random(550,8000);
    keyValueStore.find(r);
    Serial.println(keyValueStore.size());
    keyValueStore.erase(r);
    Serial.println(keyValueStore.size());
    keyValueStore.insert(r,"bla");
  }
  //clean the store
  Serial.println(keyValueStore.size());
  keyValueStore.clear();
  Serial.println(keyValueStore.size());
}`

**Comment by BojanJurca** [comment]
I fixed it. Please download the latest keyValuePairs.h file.

**Comment by Wingsofcourage** [comment]
Thanks a lot. 
Works perfekt.
